TOPLEVEL_LANG := verilog
SIM ?= verilator
TOPLEVEL := wire_buffer_gearbox_eth_ipv4_udp_mold_framer_top
COCOTB_TEST_MODULES := test_mold_framer_composition
VERILOG_SOURCES := $(abspath ../../rtl/common/wire_ingress_buffer.sv) \
 $(abspath ../../rtl/arch_a/wire_gearbox_64to8.sv) \
 $(abspath ../../rtl/arch_a/wire_eth_parser.sv) \
 $(abspath ../../rtl/arch_a/wire_ipv4_parser.sv) \
 $(abspath ../../rtl/arch_a/wire_udp_parser.sv) \
 $(abspath ../../rtl/arch_a/wire_mold_header_seq.sv) \
 $(abspath ../../rtl/arch_a/wire_mold_message_framer.sv) \
 $(abspath ../../rtl/arch_a/wire_buffer_gearbox_eth_ipv4_udp_mold_framer_top.sv)
COMPILE_ARGS += --language 1800-2012
include $(shell cocotb-config --makefiles)/Makefile.sim
