TOPLEVEL_LANG := verilog
SIM ?= verilator
TOPLEVEL := wire_mold_itch_top
SIM_BUILD := sim_build_composition
COCOTB_TEST_MODULES := test_mold_itch_composition
VERILOG_SOURCES := $(abspath ../../rtl/arch_a/wire_mold_header_seq.sv) \
 $(abspath ../../rtl/arch_a/wire_mold_message_framer.sv) \
 $(abspath ../../rtl/arch_a/wire_itch_decoder.sv) \
 $(abspath ../../rtl/arch_a/wire_mold_itch_top.sv)
COMPILE_ARGS += --language 1800-2012
include $(shell cocotb-config --makefiles)/Makefile.sim
